# Generated by Django 5.0.7 on 2024-08-20 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FilesUploadModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='static\\EncryptedFiles')),
                ('filename', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('public_key', models.TextField()),
                ('private_key', models.TextField()),
                ('filedata', models.BinaryField()),
                ('time', models.DateTimeField()),
                ('status', models.CharField(default='Encrypted', max_length=100)),
            ],
            options={
                'db_table': 'FilesUploadModel',
            },
        ),
        migrations.CreateModel(
            name='RequestFileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fid', models.IntegerField(null=True)),
                ('file', models.FileField(upload_to='static\\DecryptedFiles')),
                ('filename', models.CharField(max_length=100)),
                ('uploadedemail', models.EmailField(max_length=254)),
                ('private_key', models.TextField(null=True)),
                ('filedata', models.TextField()),
                ('requestedemail', models.EmailField(max_length=254)),
                ('time', models.DateTimeField()),
                ('status', models.CharField(default='Decrypted', max_length=100)),
            ],
            options={
                'db_table': 'RequestFileModel',
            },
        ),
        migrations.CreateModel(
            name='UsersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=100)),
                ('contact', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('profile', models.FileField(upload_to='static\\userprofiles')),
                ('status', models.CharField(default='pending', max_length=100)),
            ],
            options={
                'db_table': 'UsersModel',
            },
        ),
    ]
