# Generated by Django 5.1.7 on 2025-03-28 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='A_Cloud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='static\\EncryptedFiles')),
                ('filename', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('key', models.BinaryField()),
                ('filedata', models.BinaryField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Encrypted', max_length=100)),
            ],
            options={
                'db_table': 'A_Cloud',
            },
        ),
        migrations.CreateModel(
            name='B_Cloud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filedata', models.BinaryField()),
                ('cloud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.a_cloud')),
            ],
            options={
                'db_table': 'B_Cloud',
            },
        ),
        migrations.DeleteModel(
            name='FilesUploadModel',
        ),
    ]
