# Generated by Django 5.1.7 on 2025-03-28 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_a_cloud_b_cloud_delete_filesuploadmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecryptModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Decrypted', max_length=100)),
            ],
            options={
                'db_table': 'DecryptModel',
            },
        ),
        migrations.DeleteModel(
            name='RequestFileModel',
        ),
        migrations.AlterField(
            model_name='a_cloud',
            name='filedata',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='b_cloud',
            name='filedata',
            field=models.TextField(),
        ),
        migrations.AddField(
            model_name='decryptmodel',
            name='data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.b_cloud'),
        ),
    ]
