# Generated by Django 5.1.7 on 2025-03-28 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_decryptmodel_delete_requestfilemodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='decryptmodel',
            name='decrypted_data',
            field=models.TextField(null=True),
        ),
    ]
