# Generated by Django 5.2 on 2025-06-05 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_decryptmodel_decrypted_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersmodel',
            name='address',
        ),
        migrations.RemoveField(
            model_name='usersmodel',
            name='contact',
        ),
    ]
